<neoscript src="neo_assets/js/nouislider.min.js"></neoscript>
<div class="range-holder">
    <div id="range"></div>
    <script>
        var range = document.getElementById('range');

        noUiSlider.create(range, {
            start: [10, 500],
            connect: true,
            step: 10,
            range: {
                'min': [10],
                'max': [400]
            },
            pips: {mode: 'count', values: 2},
            tooltips: true //
        });

        range.noUiSlider.on('update', function (values, handle) {
            //console.log(values);
        });
    </script>
</div>