<!DOCTYPE html>
<html>
<!-- begin::Head -->
<head>
    (meta-tag)

    <!-- Include all css link -->
    <meta charset="utf-8"/>
    <meta name="description" content="Latest updates and statistic charts">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    (style)
    (top-script)
    (title)
</head>
<!-- end::Head -->
<!-- end::Body -->
<body class="neo-styles http">
    <div class="holder">
        <div class="content">
            <neo-content></neo-content>
        </div>
    </div>
</body>
(bottom-script)
<!-- end::Body -->
</html>
