<div class="tag-input-holder">
    <ul class="tag-list">
        <li>
            <p>ورزشی</p>
            <i class="icon neo-navigation-close"></i>
        </li>
        <li>
            <p>ورزشی</p>
            <i class="icon neo-navigation-close"></i>
        </li>
        <li>
            <p>ورزشی</p>
            <i class="icon neo-navigation-close"></i>
        </li>
        <li>
            <input name="tag" type="text" placeholder="نام تگ">
        </li>
    </ul>
</div>
