<neocss src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"></neocss>
<neoscript src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></neoscript>
<div class="map-holder" id="map-holder">

</div>
<script>
    var mymap = L.map('map-holder').setView([51.505, -0.09], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(mymap);
</script>
