<div class="before">
    <ul class="file-holder">
        <li>
            <img src="/files/test/1.png" alt="Calendar">
            <div class="progress-holder"></div>
        </li>
        <li>
            <img src="/files/test/1.png" alt="Calendar">
            <div class="progress-holder"></div>
        </li>
        <li>
            <img src="/files/test/1.png" alt="Calendar">
            <div class="progress-holder"></div>
        </li>
        <li>
            <img src="/files/test/1.png" alt="Calendar">
            <div class="progress-holder"></div>
        </li>
    </ul>
</div>
<input type="file" name="uploader" class="hidden" multiple>
<div class="upload-holder hidden">
    <i class="icon neo-cloud-upload"></i>
    <h6>برای بارگذاری، فایل خود را در این مکان بکشید و یا روی آن کلیک کنید.</h6>
</div>