<!DOCTYPE html>
<html dir="ltr">
<head>
    (meta-tag)

    <!-- Include all css link -->
    <meta charset="utf-8"/>
    <meta http-equiv="CONTENT-LANGUAGE" content="fa" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    (style)
    (top-script)
    (title)
    <neo-seo-tags display="pure"></neo-seo-tags>
</head>
<body class="neo-styles http">

<div class="holder">
    <div class="content">
        <neo-content></neo-content>
    </div>
</div>

</body>
(bottom-script)
</html>
